### ISSUE TITLE
sqlite Version compare

### ISSUE THREAD

**Issue by sasky** [silverstripe/silverstripe-sqlite3#56]
Hello. Im having trouble with this function on the classSQLite3Database
```
    public function supportsTransactions()
    {
        return version_compare($this->getVersion(), '3.6', '>=');
    }
```
I'm running the latest stable version of sqlite which confusingly is 3.25.3 
so that version compare fails.
Seems like sqlite changed their versioning system back in 2015. So  3.25.3  should be much greater than 3.6.

https://www.sqlite.org/versionnumbers.html

https://sqlite.org/chronology.html

**Comment by robbieaverill** [comment]
It seems like it's working to me: https://eval.in/1062760 - am I missing something?

**Comment by sasky** [comment]
Ha, oh sorry. I guess I just amused that was the bit that wasn't working. My bad. I feel dumb.
When I am using sql to test in the cli. I hit this error
```
    public function transactionDepth()
    {
        // Placeholder error for transactional DBs that don't expose depth
        if ($this->supportsTransactions()) {
            user_error(get_class($this) . " does not support transactionDepth", E_USER_WARNING);
        }
        return 0;
    }
``` from SilverStripe\ORM\Connect\Database

adding these two functions to SilverStripe\SQLite\SQLite3Database has sorted it out.

```
    public function supportsTransactions()
    {
        return true;
    }
    
    public function transactionDepth()
    {
        return true;
    }
```
Does that need to be a seperate issue ? Or am I still being dumb?

**Comment by robbieaverill** [comment]
I think it's pretty unlikely that you're being dumb. Which version of SilverStripe 4 are you using? For 4.2 (?) or above you need to use silverstripe/postgresql 2.1 rather than 2.0

**Comment by sasky** [comment]
Oh, I'm using 4.2
I'm mot using any version of silverstripe/postgresql. 
Sorry but what does postgresql have todo with sqlite? I don't see that as a dependancy?

**Comment by robbieaverill** [comment]
Sorry, I mixed up the DB adapters. Try 2.1 of sqlite

**Comment by sasky** [comment]
Ha, makes sense. Cheers

**Comment by maxime-rainville** [comment]
@sasky Did using version 2.1 solve your issue?

**Comment by sasky** [comment]
@maxime-rainville  yes it did, Thanks
