### ISSUE TITLE
CMS5: Make SQLite compatible

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-sqlite3#68]
## Acceptance criteria
- [ ] CMS5 build is green
- [x] CMS5 build runs framework tests
- [x] Any removed API in the CMS5 branch is marked as deprecated in the CMS4 branch
- [ ] Our CI is updated so you can install SQLite

## PRs
- https://github.com/silverstripe/recipe-kitchen-sink/pull/35
- https://github.com/silverstripe/silverstripe-sqlite3/pull/69
- https://github.com/silverstripe/gha-ci/pull/58
- https://github.com/silverstripe/silverstripe-framework/pull/10713
- https://github.com/silverstripe/silverstripe-framework/pull/10714

**Comment by maxime-rainville** [comment]
Just a couple extra notes here:
- Our GitHub action CI does not currently support SQLite. Given that it's not something we actively want to support, I don't think it's worthwhile spending a lot of time getting it set up. I suggest spending 30 min to see if it's possible. If there's no obvious solution, I'm content with running the SQLite test locally and calling it a day.
- Because SQLite is a database adapter, all of its test should be covered by the ORM tests in framework.
- I recall some broken test in SQLite in CMS4. I don't think there were a big problem, so we ignored them. As long as it's mostly functional, I'm happy to merge the PR with some test failing.
- From memory, to get the module working you need to define a `SS_SQLITE_DATABASE_PATH` variable and set `SS_DATABASE_CLASS=SQLite3Database`
- The primary use case for this database adapter is to run tests. I don't thing there's anyone that actually use it to run tests.
- I had a go at creating an action that allows you to pick whatever DB adapter you want a while a ago. [This is the snippet I use to install SQLite](https://github.com/maxime-rainville/silverstripe-ci-db/blob/06288af0bea49881fd143f5c47e760612fb8332f/action.yml#L143-L148). From what I'm reading there, it looks like it's built into the GitHub action image ... so you might not need to do any sorcery to get it working.

**Comment by sabina-talipova** [comment]
https://github.com/silverstripe/gha-ci/pull/58 should be merged first.
